import "./globals.css";
import { Pixelify_Sans } from 'next/font/google';

const PixelFont = Pixelify_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-pixel',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={PixelFont.variable}>
        {children}
      </body>
    </html>
  );
}
